{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b4879ea9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (1.56.0)\n",
      "Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from streamlit) (6.0.0)\n",
      "Requirement already satisfied: blinker<2,>=1.5.0 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from streamlit) (1.9.0)\n",
      "Requirement already satisfied: cachetools<8,>=5.5 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from streamlit) (7.0.5)\n",
      "Requirement already satisfied: click<9,>=7.0 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from streamlit) (8.0.4)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from streamlit) (3.1.46)\n",
      "Requirement already satisfied: numpy<3,>=1.23 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from streamlit) (1.24.3)\n",
      "Requirement already satisfied: packaging>=20 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from streamlit) (23.1)\n",
      "Requirement already satisfied: pandas<4,>=1.4.0 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from streamlit) (2.0.3)\n",
      "Requirement already satisfied: pillow<13,>=7.1.0 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from streamlit) (9.4.0)\n",
      "Requirement already satisfied: pydeck<1,>=0.8.0b4 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from streamlit) (0.9.1)\n",
      "Requirement already satisfied: protobuf<8,>=3.20 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from streamlit) (7.34.1)\n",
      "Requirement already satisfied: pyarrow>=7.0 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from streamlit) (11.0.0)\n",
      "Requirement already satisfied: requests<3,>=2.27 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from streamlit) (2.31.0)\n",
      "Requirement already satisfied: tenacity<10,>=8.1.0 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from streamlit) (8.2.2)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from streamlit) (6.3.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.10.0 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from streamlit) (4.15.0)\n",
      "Requirement already satisfied: watchdog<7,>=2.1.5 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from streamlit) (2.1.6)\n",
      "Requirement already satisfied: jinja2 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.2)\n",
      "Requirement already satisfied: jsonschema>=3.0 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.17.3)\n",
      "Requirement already satisfied: narwhals>=1.27.1 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.19.0)\n",
      "Requirement already satisfied: colorama in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
      "Requirement already satisfied: smmap<6,>=3.0.1 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from pandas<4,>=1.4.0->streamlit) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from pandas<4,>=1.4.0->streamlit) (2023.3.post1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from pandas<4,>=1.4.0->streamlit) (2023.3)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from requests<3,>=2.27->streamlit) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from requests<3,>=2.27->streamlit) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from requests<3,>=2.27->streamlit) (1.26.16)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from requests<3,>=2.27->streamlit) (2023.7.22)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.1.1)\n",
      "Requirement already satisfied: attrs>=17.4.0 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (22.1.0)\n",
      "Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.18.0)\n",
      "Requirement already satisfied: six>=1.5 in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.16.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install streamlit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8342dd43",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "7b76adb7",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-04-08 15:07:36.973 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:36.975 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.477 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-04-08 15:07:37.477 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.477 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.479 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.479 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.481 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.483 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.484 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.485 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.486 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.488 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.488 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.490 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.490 Session state does not function when running a script without `streamlit run`\n",
      "2026-04-08 15:07:37.490 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.490 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.492 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.492 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.494 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.494 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.494 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.494 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.496 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.496 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.496 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.496 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.500 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.500 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.501 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.502 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.502 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.502 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.504 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.504 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.504 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.504 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.506 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.506 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.506 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.506 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.508 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.508 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.508 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.508 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.510 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.512 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.512 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.514 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.514 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.514 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.514 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.516 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.516 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.516 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.517 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.518 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.518 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.518 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.520 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.520 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.520 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.522 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-04-08 15:07:37.522 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.522 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.522 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.524 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.524 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.524 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.524 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.526 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.526 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.526 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.526 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-08 15:07:37.528 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# Load trained model\n",
    "model = joblib.load(\"Credit_Card_Fraud_model.pkl\")\n",
    "\n",
    "st.set_page_config(page_title=\"Fraud Detection App\", layout=\"wide\")\n",
    "\n",
    "st.title(\"💳 Credit Card Fraud Detection\")\n",
    "st.write(\"Detect whether a transaction is *Fraudulent or Legitimate*\")\n",
    "\n",
    "# Sidebar\n",
    "st.sidebar.header(\"Choose Input Method\")\n",
    "option = st.sidebar.radio(\"Select Option\", [\"Manual Input\", \"Upload CSV\"])\n",
    "\n",
    "# ===============================\n",
    "# 🔹 Manual Input\n",
    "# ===============================\n",
    "if option == \"Manual Input\":\n",
    "    st.subheader(\"Enter Transaction Details\")\n",
    "\n",
    "    amount = st.number_input(\"Transaction Amount\", min_value=0.0)\n",
    "\n",
    "    # Example V1–V5 (extend if needed)\n",
    "    v1 = st.number_input(\"V1\")\n",
    "    v2 = st.number_input(\"V2\")\n",
    "    v3 = st.number_input(\"V3\")\n",
    "    v4 = st.number_input(\"V4\")\n",
    "    v5 = st.number_input(\"V5\")\n",
    "\n",
    "    if st.button(\"Predict\"):\n",
    "        input_data = np.array([[amount, v1, v2, v3, v4, v5]])\n",
    "\n",
    "        prediction = model.predict(input_data)\n",
    "\n",
    "        if prediction[0] == 1:\n",
    "            st.error(\"🚨 Fraud Transaction Detected!\")\n",
    "        else:\n",
    "            st.success(\"✅ Legitimate Transaction\")\n",
    "\n",
    "# ===============================\n",
    "# 🔹 CSV Upload\n",
    "# ===============================\n",
    "elif option == \"Upload CSV\":\n",
    "    st.subheader(\"Upload CSV File\")\n",
    "\n",
    "    file = st.file_uploader(\"Upload your dataset\", type=[\"csv\"])\n",
    "\n",
    "    if file is not None:\n",
    "        data = pd.read_csv(file)\n",
    "        st.write(\"📄 Uploaded Data:\", data.head())\n",
    "\n",
    "        if st.button(\"Predict All\"):\n",
    "            try:\n",
    "                predictions = model.predict(data)\n",
    "\n",
    "                data[\"Prediction\"] = predictions\n",
    "                data[\"Prediction\"] = data[\"Prediction\"].map({\n",
    "                    0: \"Legitimate\",\n",
    "                    1: \"Fraud\"\n",
    "                })\n",
    "\n",
    "                st.write(\"✅ Results:\", data.head())\n",
    "\n",
    "                # Download results\n",
    "                csv = data.to_csv(index=False).encode('utf-8')\n",
    "                st.download_button(\n",
    "                    label=\"Download Results\",\n",
    "                    data=csv,\n",
    "                    file_name=\"predictions.csv\",\n",
    "                    mime=\"text/csv\"\n",
    "                )\n",
    "\n",
    "            except Exception as e:\n",
    "                st.error(f\"Error: {e}\")\n",
    "\n",
    "# ===============================\n",
    "# Footer\n",
    "# ===============================\n",
    "st.markdown(\"---\")\n",
    "st.write(\"Built with ❤️ using Streamlit\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "e3a134fe",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pip in C:\\Users\\atish chavan\\anaconda3\\Lib\\site-packages (26.0.1)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install --upgrade pip"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0ac00f03",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
